console.log('Heyy!')
console.log('Welcome to TATA Strive')
setTimeout(() => {console.log('Hi')},3000)
setTimeout(() => {console.log('Hello')},2000)
setTimeout(() => {console.log('Hello')},4000)
console.log('Heyy!')
setTimeout(() => {console.log('Welcome to TATA Strive')},1500)